services:
    ngninx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - internal
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./src:/var/www/html
            - ./logs/nginx:/var/log/nginx/
        depends_on:
            - php-fpm
    php-fpm:
        build: .
        container_name: php-fpm
        networks:
            - internal
        env_file:
            - .env
        volumes:
            - ./src:/var/www/html
        depends_on:
            - db
    # phpmyadmin:
    #     image: phpmyadmin
    #     container_name: phpmyadmin
    #     ports:
    #         - 8080:80
    #     networks:
    #         - internal
    #     env_file:
    #         - .env
    #     environment:
    #         - PMA_HOST=db
    #         - PMA_USER=${MYSQL_USER}
    #         - PMA_PASSWORD=${MYSQL_PASSWORD}
    #         - PMA_ARBITRARY=1
    #     depends_on:
    #         - db
    db:
        image: mysql:8.2
        container_name: db
        env_file:
            - .env
        networks:
            - internal
        volumes:
            - ./dbdata:/var/lib/mysql/
            - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    internal:
        driver: bridge
